# Generated by Django 2.0.7 on 2019-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=20, verbose_name='用户名')),
                ('password', models.CharField(default=None, max_length=20, verbose_name='密码')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='邮箱')),
                ('is_active', models.CharField(choices=[('1', '已激活'), ('0', '未激活')], default='0', max_length=1, verbose_name='是否激活')),
                ('img_teacher', models.ImageField(default='teacher_img/校徽.png', upload_to='teacher_img/', verbose_name='头像')),
                ('academy', models.CharField(choices=[('信息与计算机学院', '信息与计算机学院'), ('政法学院', '政法学院'), ('数学学院', '数学学院')], default='信息与计算机学院', max_length=20, verbose_name='学院')),
                ('level', models.CharField(choices=[('0', '本科生'), ('1', '研究生')], default='0', max_length=10, verbose_name='年级')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
